### ISSUE TITLE
How to read the contents of a message?

### ISSUE THREAD

**Issue by cjm-droid** [dubek/rabbitmq-dump-queue#12]
I was able to create the message files, but when I open them in a text editor all I see is garbled characters.  How do I decode these messages so I can read them?

**Comment by dubek** [comment]
@cjm-droid : The content of the message is copied as-is from what is stored in the RabbitMQ server. In order to find out how to decode the message you get, you'll need to find out who/what is publishing those messages and ask them. RabbitMQ allows messages which can be any binary data. There's a `Content-Type` header which might be useful but it's not mandatory.
